### ISSUE TITLE
Update summary for the benchmark?

### ISSUE THREAD

**Issue by hellowangqian** [jump-cellpainting/2024_Chandrasekaran_NatureMethods#75]
Dear author,
Many thanks for releasing the data and code for such a great project. I've been following the repository for a while and am trying to reproducing the results for the "benchmark". I just realised the code and results have been updated recently. I'm wondering if you could provide a summary of what has changed. That would be a big help for people like me to understand the evaluation metrics and beyond better.
Particularly, I'd like to know how to interpret the **negative** values of mmAP in these [results](https://github.com/jump-cellpainting/2023_Chandrasekaran_submitted/blob/main/benchmark/output/cellprofiler_gene_compound_matching_mmap.csv)?
Best wishes

**Comment by hellowangqian** [comment]
Hi @niranjchandrasekaran, many thanks for your prompt reply. This clarifies most of my confusion but the one I added in the last sentence of my original post: why the mAP/mmAP are negative values? How to interpret these results? According to the definition of mAP, it should be always positive and even being subtracted by the baseline, it should be close to 0 rather than being "very negative" (e.g., <-0.1). Is there anything I miss here?

**Comment by niranjchandrasekaran** [comment]
Hi @hellowangqian, the way we define our baseline, which is the 95th percentile of AP values of 10k randomly ranked lists, we do end up with baseline AP values that can sometimes be larger than that of the treatments. That results in AP values being negative. The way we think about them is that any treatment with an AP value that is less than or equal to zero is indistinguishable from the reference (either negative control or other treatments in the experiment). We are working on an alternate approach that would avoid these negative AP values and is more interpretable, but that was not used in this manuscript/repo.

**Comment by hellowangqian** [comment]
Great explanation. Everything is clear now. Thank you again.

**Comment by badtom** [comment]
Hi, perhaps you can simply use the AP values minus the performance of a random classifier (which is the percentage of positive points in the query set) similarly as done for areas under the precision-recall curves (AUPRC) in https://openreview.net/pdf?id=701FtuyLlAd . In this way you need no shuffled ranked lists and from averaging over classes you will see if a method is performing better than a random baseline on average (i.e. the average is > 0).

**Comment by niranjchandrasekaran** [comment]
> perhaps you can simply use the AP values minus the performance of a random classifier (which is the percentage of positive points in the query set) similarly as done for areas under the precision-recall curves (AUPRC)

Hi @badtom, [we initially used that approach](https://github.com/jump-cellpainting/2023_Chandrasekaran_submitted/blob/a1b512814403f6ea5fbc863b930539f2b36aa310/benchmark/utils.py#L440-L442) to correct the mAP values but found that the percentage of positive points was closer to the median of the distribution of mAP values of the random classifier. We also found that the distribution had a long tail, and using the median to summarize that distribution resulted in too many false positives. Hence, we switched over to using the 95th percentile of the distribution.

**Comment by badtom** [comment]
Thank you for the information. I did some search on the topic and found out that, as opposed to AUPRC (https://itnext.io/the-baseline-for-precision-recall-curve-a-bayesian-approach-1611c690607) for AP the percentage of positive points is only an approximate performance of random baseline, but some corrections can be computed as discussed in  https://ufal.mff.cuni.cz/pbml/103/art-bestgen.pdf. Perhaps this is the reason for the discrepancies you observed? Also it is not clear for me the distribution of what had a long tail and what you mean by false positives in the above comment, hope I will better understand it from the updated manuscript.

**Comment by niranjchandrasekaran** [comment]
Hi @badtom, the manuscript that I previously mentioned is now up on biorxiv: https://www.biorxiv.org/content/10.1101/2024.04.01.587631v1. Since my last comment, we have updated our approach to calculating mAP. I hope this manuscript clarifies some of your questions.
