### ISSUE TITLE
MAP and FR

### ISSUE THREAD

**Issue by 2673380801** [jump-cellpainting/2024_Chandrasekaran_NatureMethods#89]
Dear author, could you please explain the principle of map calculation in downstream analysis task in detail? I am still confused after reading the paper and code.

**Comment by niranjchandrasekaran** [comment]
Hi @2673380801, the following is a description of our metrics from the updated version of our manuscript. If it is still unclear, please do let me know. I can share an upcoming manuscript which is all about the mAP metric (once it is up on biorxiv).

> Average precision (AP) serves as our primary metric for both replicability (how distinguishable are replicates of a perturbation from negative controls) and biological relevance (how distinguishable are sister perturbations from other perturbations). We measure similarity between profiles using cosine similarity or absolute value of cosine similarity for cases where both positive and negative correlations are considered matches. To calculate AP, we first construct a binary ranking of sample and negative control profiles by their cosine similarities. Based on this rank list, calculation of the AP score follows the common formulation in the field, i.e. we average precision values at each rank k where recall changes:
> $$AP=\sum_k(R_k-R_{k-1})P_k$$
> 
> We then assign a p-value to each AP score by a permutation-based significance testing approach. Specifically, we assess the significance of the AP score against a null distribution built by randomly shuffling the rank list 100,000 times and computing corresponding random AP scores. These p-values are then adjusted for multiple testing using the Benjamini-Hochberg procedure to obtain corrected p-values (which we refer to as q-values).
> 
> We also compute mean Average Precision (mAP) by averaging AP scores per each class, where “class” refers to either a specific perturbation (for replicability) or perturbations associated with the same gene (for biological relevance). We report a per-class mAP value along with a combined q-value obtained by taking the geometric mean of the q-values. Finally, we summarize the mAP values for a specific task by calculating the fraction of classes with q-values below the significance threshold (0.05), termed Fraction Retrieved (FR).

**Comment by 2673380801** [comment]
> Average precision (AP) serves as our primary metric for both replicability (how distinguishable are replicates of a perturbation from negative controls) and biological relevance (how distinguishable are sister perturbations from other perturbations). We measure similarity between profiles using cosine similarity or absolute value of cosine similarity for cases where both positive and negative correlations are considered matches. To calculate AP, we first construct a binary ranking of sample and negative control profiles by their cosine similarities. Based on this rank list, calculation of the AP score follows the common formulation in the field, i.e. we average precision values at each rank k where recall changes:

Thank you for your explanation, but I still have some confusion, mainly because I may lack some knowledge and have some confusion about the design of the calculation. However, I am eager to understand it because I am very interested in this dataset. In order to understand the calculation, I looked at the specific calculation code, which uses functions from copairs, but I couldn't find the corresponding implementation for some functions, perhaps because the repository has been updated? After going through the build_rank_lists function, it seems to produce a nested list with many 0 and 1. Although I can roughly understand the description in the paper, the specific output of the code implementation confuses me. Perhaps knowing the meaning of the results obtained by this function would greatly help me understand the calculation.

**Comment by niranjchandrasekaran** [comment]
Thank you for your interest in this dataset. Copairs has had many updates since it was used in this repo, so some functions may have moved. [Here](https://github.com/cytomining/copairs/blob/200d24d612ef66e53076e5e78c4edd4f2fa93311/src/copairs/map/average_precision.py#L15) is the implementation of the `build_rank_lists` function that we used in this repo. I am tagging @johnarevalo, the author of copairs, who may be able to briefly explain the output of this function.

**Comment by johnarevalo** [comment]
Sure! this function creates the rank lists used to compute average precision. In term of information retrieval, 0 represents "irrelevant documents" (in this case the negative controls), and 1 represents "relevant documents" (in this case the replicates).

We implemented it in a vectorized manner for efficiency reasons, so a single 1d np.array contains the rank lists for all the samples. The outputs are:
 
 - `paired_ix`: numpy array containing indices of the samples in the `meta` DataFrame in the `average_precision` function.
 - `rel_k_list`: np.array containing all the rank lists concatenated.
 - `counts`: the size of every rank list associated to the `paired_ix` array. It has the same shape as `paired_ix`

e.g the following output:
```
paired_ix = [7, 9, 12]
rel_k_list = [0, 1, 1, 0,    0, 1, 0,    1, 1, 0, 0, 1] # spaces just for visualization
counts = [4, 3, 5]
```

means the sample in row `7` of `meta` was compared with 4 other samples in the database (2 negative controls, 2 replicates) and the replicates took second and third position (`[0, 1, 1, 0]`)

Similarly, row 9 was compared with 2 negcons and 1 replicate `[0, 1, 0]`, and row 12 was compared with 2 negcons and 3 replicates (`[1, 1, 0, 0, 1]`)

**Comment by 2673380801** [comment]
> Thank you for your interest in this dataset. Copairs has had many updates since it was used in this repo, so some functions may have moved. [Here](https://github.com/cytomining/copairs/blob/200d24d612ef66e53076e5e78c4edd4f2fa93311/src/copairs/map/average_precision.py#L15) is the implementation of the `build_rank_lists` function that we used in this repo. I am tagging @johnarevalo, the author of copairs, who may be able to briefly explain the output of this function.


> Sure! this function creates the rank lists used to compute average precision. In term of information retrieval, 0 represents "irrelevant documents" (in this case the negative controls), and 1 represents "relevant documents" (in this case the replicates).
> 
> We implemented it in a vectorized manner for efficiency reasons, so a single 1d np.array contains the rank lists for all the samples. The outputs are:
> 
> * `paired_ix`: numpy array containing indices of the samples in the `meta` DataFrame in the `average_precision` function.
> * `rel_k_list`: np.array containing all the rank lists concatenated.
> * `counts`: the size of every rank list associated to the `paired_ix` array. It has the same shape as `paired_ix`
> 
> e.g the following output:
> 
> ```
> paired_ix = [7, 9, 12]
> rel_k_list = [0, 1, 1, 0,    0, 1, 0,    1, 1, 0, 0, 1] # spaces just for visualization
> counts = [4, 3, 5]
> ```
> 
> means the sample in row `7` of `meta` was compared with 4 other samples in the database (2 negative controls, 2 replicates) and the replicates took second and third position (`[0, 1, 1, 0]`)
> 
> Similarly, row 9 was compared with 2 negcons and 1 replicate `[0, 1, 0]`, and row 12 was compared with 2 negcons and 3 replicates (`[1, 1, 0, 0, 1]`)


Thank you for your explanation.Now I understand.

**Comment by niranjchandrasekaran** [comment]
Hi @2673380801, we now have a manuscript that describes the mAP metric in more detail: https://www.biorxiv.org/content/10.1101/2024.04.01.587631v1
