### ISSUE TITLE
missing copairs and share of ready-to-use data

### ISSUE THREAD

**Issue by feng-bao-ucsf** [jump-cellpainting/2024_Chandrasekaran_NatureMethods#91]
Congrats on the great work. I am trying to run the benchmark code and found a package called copairs missing, can you provide more information?
Furthermore, do you have a csv file [meta+feature] aggregating files across plates (or some of them) that we can directly load?

Many thanks!
Feng

**Comment by niranjchandrasekaran** [comment]
Hi @feng-bao-ucsf, thank you for your interest in our dataset!

> Congrats on the great work. I am trying to run the benchmark code and found a package called copairs missing, can you provide more information?

You can find an [environment file](https://github.com/jump-cellpainting/2024_Chandrasekaran_NatureMethods/blob/main/benchmark/environment.yml) in the `benchmark` folder that you can set up with conda. The version of copairs that we use for computing metrics is available there.

> Furthermore, do you have a csv file [meta+feature] aggregating files across plates (or some of them) that we can directly load?

Currently, we don't have such a file available, since there are several ways of partitioning the data. You may want to create such a file depending on your use case and which subset of the data that you are interested in.

Please do let me know if you have other questions.

**Comment by feng-bao-ucsf** [comment]
Thank you for the quick response!

I'm having trouble installing the `copairs` package. When I try to use the command `git+https://github.com/cytomining/copairs@880f22a551bd897896d148a0b07baa99d981c6a9`, I'm getting a `No such file or directory` error. Could you please take a look and let me know if there's anything I'm missing?

Additionally, I think it would be really helpful if the data format for this project was similar to the Rosetta project format used in your lab. Having a consistent data format would make it easier for the broader community to work with and contribute to the project.

Many thanks!

**Comment by niranjchandrasekaran** [comment]
> I'm having trouble installing the copairs package. When I try to use the command git+https://github.com/cytomining/copairs@880f22a551bd897896d148a0b07baa99d981c6a9, I'm getting a No such file or directory error. Could you please take a look and let me know if there's anything I'm missing?

I tried installing the conda environment using 

```bash
conda env create --force --file environment.yml
```

and directly using `pip install`, 

```bash
pip install https://github.com/cytomining/copairs@880f22a551bd897896d148a0b07baa99d981c6a9
```

both work for me. Can you tell me more about how you are trying to install the package and what error you encounter?

> Additionally, I think it would be really helpful if the data format for this project was similar to the Rosetta project format used in your lab. Having a consistent data format would make it easier for the broader community to work with and contribute to the project.

We are currently working towards standardizing the data formats within the lab (https://registry.opendata.aws/cellpainting-gallery/). Given the many historical datasets and the evolution of our understanding of what format works over the years, there is a lot of variation in formats from project to project. We hope the formats will be more uniform in the future. Thank you for your feedback!

**Comment by feng-bao-ucsf** [comment]
Thank you so much for the prompt reply. I will give it try.
